name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.7.0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Type check
        run: pnpm exec tsc --noEmit

      - name: Build package
        run: pnpm run build

      - name: Check build output
        run: |
          if [ ! -f "dist/viewer.js" ]; then
            echo "ES module build failed"
            exit 1
          fi
          if [ ! -f "dist/viewer.umd.cjs" ]; then
            echo "UMD build failed"
            exit 1
          fi
          if [ ! -f "dist/index.d.ts" ]; then
            echo "Type definitions failed"
            exit 1
          fi
          echo "All build outputs present ✓"

  build-storybook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.7.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Storybook
        run: pnpm run build:sb
